# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmYhlA9LRBtc5eakphHrmfpdEwikWNbr
"""

class ContactBook:
  """
  A single calss for representing a Contact Book.
  """
  def __init__(self):
    """
    Give the contact book object a dictionary
    """
    self.contacts: dict = {}

  def add_contact(self, name: str, phone: str, email: str, address: str):
    """
    Add a contact to the contact book.

    :param str name: The name of the contact.
    :param str phone: The phone number of the contact.
    :param str email: The email address of the contact.
    :param str address: The address of the contact.
    """
    if name not in self.contacts:
      self.contacts[name] = {
        "phone": phone,
        "email": email,
        "address": address
      }
      print("Added contact successfully")
    else:
      print("Contact already exists")

  def view_contacts(self):
    """
    View all the contacts in the contact book.
    """
    for name, info in self.contacts.items():
      print("Name:", name)
      print("Phone number:", info["phone"])
      print("Email address:", info["email"])
      print("Address:", info["address"])
      print("-" * 100)

  def delete_contact(self, name: str):
    """
    Delete a contact from the contact book.

    :param str name: The name of the contact to delete.
    """
    if name in self.contacts:
      del self.contacts[name]
      print("Contact deleted successfully")
    else:
      print("Contact does not exist")

  def edit_contact(self, name: str, phone: str = None, email: str = None, address: str = None):
    if name in self.contacts:
      if phone:
        self.contacts[name]["phone"] = phone
      if email:
        self.contacts[name]["email"] = email
      if address:
        self.contacts[name]["address"] = address
        return
    print("Contact does not exist")

if __name__ == "__main__":
  book = ContactBook()

  while True:
    print("\n---Contact Book Application---")
    print("1. Add Contact")
    print("2. View Contacts")
    print("3. Delete Contact")
    print("4. Edit Contact")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
      name = input("\nEnter name: ")
      phone = input("Enter phone number: ")
      email = input("Enter email address: ")
      address = input("Enter address: ")
      book.add_contact(name, phone, email, address)

    elif choice == "2":
      print("\nList of contacts:")
      book.view_contacts()

    elif choice == "3":
      name = input("\nEnter name of contact to delete: ")
      book.delete_contact(name)

    elif choice == "4":
      name = input("\nEnter name of contact to edit: ")
      phone = input("Enter new phone number (press enter to skip): ")
      email = input("Enter new email address (press enter to skip): ")
      address = input("Enter new address (press enter to skip): ")
      book.edit_contact(name, phone, email, address)

    elif choice == "5":
      print("Exiting...")
      break

    else:
      fprint("Invalid choice. Please try again.")

from google.colab import drive
drive.mount('/content/drive')